using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace FamidashEditor;

internal static class MesenNesIntegration
{
	private const string RamCapPrefix = "RAMCAP|";

	internal static void LaunchGui(string mesenExePath, string romPath)
	{
		if (string.IsNullOrWhiteSpace(mesenExePath))
		{
			throw new InvalidOperationException("Mesen executable path is not configured.");
		}
		if (string.IsNullOrWhiteSpace(romPath))
		{
			throw new InvalidOperationException("Famidash ROM path is not configured.");
		}
		if (!File.Exists(mesenExePath))
		{
			throw new FileNotFoundException("Mesen executable not found.", mesenExePath);
		}
		if (!File.Exists(romPath))
		{
			throw new FileNotFoundException("ROM file not found.", romPath);
		}
		ProcessStartInfo startInfo = new ProcessStartInfo(mesenExePath, QuoteArg(romPath))
		{
			UseShellExecute = false,
			CreateNoWindow = false,
			WorkingDirectory = (Path.GetDirectoryName(mesenExePath) ?? Environment.CurrentDirectory)
		};
		Process.Start(startInfo);
	}

	internal static MesenRamCaptureResult CaptureRam(MesenRamCaptureOptions options)
	{
		Validate(options);
		Directory.CreateDirectory(Path.GetDirectoryName(options.OutputPath) ?? Environment.CurrentDirectory);
		string text = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Famidash Editor", "Replays");
		Directory.CreateDirectory(text);
		string text2 = Path.Combine(text, "famidash-mesen-ramcap.lua");
		File.WriteAllText(text2, BuildLuaScript(options), Encoding.UTF8);
		string arguments = string.Join(" ", "--doNotSaveSettings", "--testRunner", QuoteArg(text2), QuoteArg(options.RomPath), "--timeout=" + Math.Max(10, options.TimeoutSeconds).ToString(CultureInfo.InvariantCulture));
		ProcessStartInfo startInfo = new ProcessStartInfo(options.MesenExePath, arguments)
		{
			UseShellExecute = false,
			CreateNoWindow = true,
			RedirectStandardOutput = true,
			RedirectStandardError = true,
			WorkingDirectory = (Path.GetDirectoryName(options.MesenExePath) ?? Environment.CurrentDirectory)
		};
		StringBuilder stdout = new StringBuilder();
		StringBuilder stderr = new StringBuilder();
		using Process process = new Process
		{
			StartInfo = startInfo
		};
		process.OutputDataReceived += delegate(object _, DataReceivedEventArgs e)
		{
			if (!string.IsNullOrEmpty(e.Data))
			{
				lock (stdout)
				{
					stdout.AppendLine(e.Data);
				}
			}
		};
		process.ErrorDataReceived += delegate(object _, DataReceivedEventArgs e)
		{
			if (!string.IsNullOrEmpty(e.Data))
			{
				lock (stderr)
				{
					stderr.AppendLine(e.Data);
				}
			}
		};
		if (!process.Start())
		{
			throw new InvalidOperationException("Failed to start Mesen process.");
		}
		process.BeginOutputReadLine();
		process.BeginErrorReadLine();
		process.WaitForExit();
		string stdout2;
		lock (stdout)
		{
			stdout2 = stdout.ToString();
		}
		string stdErr;
		lock (stderr)
		{
			stdErr = stderr.ToString();
		}
		int samples = WriteCaptureFile(options, stdout2);
		int stopCode = TryExtractStopCode(stdout2, process.ExitCode);
		return new MesenRamCaptureResult
		{
			ExitCode = process.ExitCode,
			StopCode = stopCode,
			Samples = samples,
			StdErr = stdErr
		};
	}

	private static void Validate(MesenRamCaptureOptions options)
	{
		if (options == null)
		{
			throw new ArgumentNullException("options");
		}
		if (string.IsNullOrWhiteSpace(options.MesenExePath) || !File.Exists(options.MesenExePath))
		{
			throw new FileNotFoundException("Mesen executable not found.", options.MesenExePath);
		}
		if (string.IsNullOrWhiteSpace(options.RomPath) || !File.Exists(options.RomPath))
		{
			throw new FileNotFoundException("ROM file not found.", options.RomPath);
		}
		if (options.Addresses == null || options.Addresses.Count == 0)
		{
			throw new InvalidOperationException("No RAM addresses configured for capture.");
		}
		if (options.MaxFrames < 1)
		{
			options.MaxFrames = 1;
		}
		if (options.SampleEveryNFrames < 1)
		{
			options.SampleEveryNFrames = 1;
		}
		if (options.TimeoutSeconds < 10)
		{
			options.TimeoutSeconds = 10;
		}
	}

	private static string BuildLuaScript(MesenRamCaptureOptions options)
	{
		string text = string.Join(", ", options.Addresses.Select((ushort a) => "0x" + a.ToString("X4", CultureInfo.InvariantCulture)));
		int num = Math.Max(1, options.MaxFrames);
		int num2 = Math.Max(1, options.SampleEveryNFrames);
		return string.Join("\n", "-- Auto-generated by FamidashEditor Mesen bridge (NES only)", "local addresses = { " + text + " }", "local maxFrames = " + num.ToString(CultureInfo.InvariantCulture), "local sampleEvery = " + num2.ToString(CultureInfo.InvariantCulture), "", "local function capture()", "  local state = emu.getState()", "  local frame = state['frameCount'] or 0", "  if frame % sampleEvery == 0 then", "    local parts = { '" + "RAMCAP|".TrimEnd('|') + "', 'f=' .. tostring(frame) }", "    for i=1,#addresses do", "      local addr = addresses[i]", "      local v = emu.read(addr, emu.memType.nesMemory)", "      parts[#parts+1] = string.format('%04X=%02X', addr, v)", "    end", "    print(table.concat(parts, '|'))", "  end", "  if frame >= maxFrames then", "    emu.stop(0)", "  end", "end", "", "emu.addEventCallback(capture, emu.eventType.endFrame)", "");
	}

	private static int WriteCaptureFile(MesenRamCaptureOptions options, string stdout)
	{
		int num = 0;
		using StreamWriter streamWriter = new StreamWriter(options.OutputPath, append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
		streamWriter.WriteLine("{\"type\":\"meta\",\"tool\":\"mesen2\",\"mode\":\"nes-testRunner\",\"rom\":\"" + EscapeJson(options.RomPath) + "\",\"frames\":" + options.MaxFrames.ToString(CultureInfo.InvariantCulture) + ",\"sampleEvery\":" + options.SampleEveryNFrames.ToString(CultureInfo.InvariantCulture) + "}");
		using StringReader stringReader = new StringReader(stdout ?? string.Empty);
		while (true)
		{
			string text = stringReader.ReadLine();
			if (text == null)
			{
				break;
			}
			if (text.StartsWith("RAMCAP|", StringComparison.Ordinal))
			{
				string text2 = ParseSampleLineToJson(text);
				if (text2.Length != 0)
				{
					streamWriter.WriteLine(text2);
					num++;
				}
			}
		}
		return num;
	}

	private static string ParseSampleLineToJson(string line)
	{
		string[] array = line.Split('|', StringSplitOptions.RemoveEmptyEntries);
		if (array.Length < 2)
		{
			return string.Empty;
		}
		int result = 0;
		List<string> list = new List<string>();
		for (int i = 1; i < array.Length; i++)
		{
			string text = array[i];
			if (text.StartsWith("f=", StringComparison.OrdinalIgnoreCase))
			{
				int.TryParse(text.Substring(2), NumberStyles.Integer, CultureInfo.InvariantCulture, out result);
				continue;
			}
			int num = text.IndexOf('=');
			if (num > 0 && num < text.Length - 1)
			{
				string value = text.Substring(0, num).ToUpperInvariant();
				string value2 = text.Substring(num + 1).ToUpperInvariant();
				list.Add("\"" + EscapeJson(value) + "\":\"" + EscapeJson(value2) + "\"");
			}
		}
		return "{\"type\":\"sample\",\"frame\":" + result.ToString(CultureInfo.InvariantCulture) + ",\"values\":{" + string.Join(",", list) + "}}";
	}

	private static int TryExtractStopCode(string stdout, int exitCode)
	{
		return exitCode;
	}

	private static string QuoteArg(string value)
	{
		return "\"" + value.Replace("\"", "\\\"") + "\"";
	}

	private static string EscapeJson(string value)
	{
		return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
	}
}
