#!/usr/bin/env python3
"""Check for FLOOR_CEIL gaps near coin and map the full corridor from cols 508-570"""
import xml.etree.ElementTree as ET, re

tree = ET.parse(r"c:\Editor Test\famidash\LEVELS\LEVEL DATA\lvlset_HUGE\kratos.tmx")
root = tree.getroot()

# Full collision table from MetatileCollision.cs
collision_names_raw = """COL_NONE COL_FLOOR_CEIL COL_FLOOR_CEIL COL_BOTTOM COL_DEATH_TOP COL_FLOOR_CEIL COL_FLOOR_CEIL COL_NONE
COL_DEATH_BOTTOM COL_DEATH_BOTTOM COL_DEATH_TOP COL_DEATH_TOP COL_DEATH_BOTTOM COL_DEATH_TOP COL_DEATH_LEFT COL_DEATH_RIGHT
COL_ALL COL_DEATH COL_DEATH_BOTTOM COL_DEATH_BOTTOM COL_DEATH_TOP COL_TOP_CENTER_SPIKE COL_ALL COL_DEATH_TOP
COL_DEATH_BOTTOM COL_TOP COL_DEATH COL_DEATH COL_DEATH COL_DEATH_LEFT COL_DEATH_TOP COL_DEATH_RIGHT
COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_NONE
COL_ALL COL_ALL COL_ALL COL_ALL COL_NONE COL_NONE COL_NONE COL_TOP_CENTER_SPIKE COL_ALL COL_ALL COL_ALL COL_DEATH_BOTTOM COL_ALL COL_ALL COL_ALL COL_ALL
COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_NONE
COL_ALL COL_ALL COL_ALL COL_ALL COL_TOP COL_TOP COL_TOP COL_TOP COL_BOTTOM COL_BOTTOM COL_BOTTOM COL_DEATH COL_DEATH_BOTTOM COL_DEATH_TOP COL_DEATH_RIGHT COL_DEATH_LEFT
COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_ALL COL_NONE
COL_ALL COL_ALL COL_ALL COL_ALL COL_DOWN_RIGHT_SPIKE COL_DEATH_BOTTOM COL_DOWN_LEFT_SPIKE COL_DEATH_RIGHT COL_NONE COL_DEATH_LEFT COL_UP_RIGHT_SPIKE COL_DEATH_TOP COL_UP_LEFT_SPIKE COL_DEATH COL_ALL COL_DEATH_BOTTOM
COL_NONE COL_NONE COL_DEATH COL_DEATH COL_DEATH_BOTTOM COL_DEATH_TOP COL_DEATH_BOTTOM COL_DEATH_TOP COL_FLOOR_CEIL COL_FLOOR_CEIL COL_RIGHT COL_LEFT COL_RIGHT COL_LEFT COL_NONE COL_NO_SIDE
COL_SLOPE_RD45 COL_SLOPE_LD45 COL_SLOPE_RU45 COL_SLOPE_LU45 COL_SLOPE_RD22_RIGHT COL_SLOPE_RD22_LEFT COL_SLOPE_LD22_RIGHT COL_SLOPE_LD22_LEFT COL_SLOPE_RU22_RIGHT COL_SLOPE_RU22_LEFT COL_SLOPE_LU22_RIGHT COL_SLOPE_LU22_LEFT COL_SLOPE_RD66_TOP COL_SLOPE_RD66_BOT COL_SLOPE_LD66_BOT COL_SLOPE_LD66_TOP
COL_SLOPE_RU66_TOP COL_SLOPE_RU66_BOT COL_SLOPE_LU66_BOT COL_SLOPE_LU66_TOP COL_NO_SIDE COL_NO_SIDE COL_NO_SIDE COL_NO_SIDE COL_LEFT_SPIKE_BLOCK COL_RIGHT_SPIKE_BLOCK COL_BOTTOM_LEFT_SPIKE COL_BOTTOM_RIGHT_SPIKE COL_BOTTOM_SPIKES COL_DOWN_LEFT_SPIKE COL_DOWN_RIGHT_SPIKE COL_DOWN_BOTH_SPIKES
COL_UP_LEFT COL_UP_RIGHT COL_DOWN_LEFT COL_DOWN_RIGHT COL_TOP COL_BOTTOM COL_LEFT COL_RIGHT COL_TOP_LEFT_STAIRS COL_TOP_RIGHT_STAIRS COL_BOTTOM_LEFT_STAIRS COL_BOTTOM_RIGHT_STAIRS COL_TOP_LEFT_BOTTOM_RIGHT COL_TOP_RIGHT_BOTTOM_LEFT COL_UP_LEFT_SPIKE COL_UP_RIGHT_SPIKE
COL_UP_BOTH_SPIKES COL_DEATH_TOP_RIGHT COL_DEATH_TOP_LEFT COL_DEATH_BOTTOM_RIGHT COL_DEATH_BOTTOM_LEFT COL_NONE COL_NONE COL_BOTTOM_CENTER_SPIKE COL_BOTTOM_CENTER_SPIKE COL_TOP COL_BOTTOM COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE
COL_NONE COL_NONE COL_NONE COL_ALL COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE COL_DOWN_RIGHT_SPIKE COL_DOWN_LEFT_SPIKE COL_UP_LEFT_SPIKE COL_UP_RIGHT_SPIKE COL_LEFT COL_RIGHT COL_UP_RIGHT
COL_RIGHT COL_TOP COL_TOP COL_UP_LEFT COL_TOP COL_RIGHT COL_BOTTOM COL_TOP COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE COL_NONE
COL_DOWN_RIGHT_SPIKE COL_DOWN_LEFT_SPIKE COL_UP_RIGHT_SPIKE COL_UP_LEFT_SPIKE COL_DOWN_RIGHT_SPIKE COL_DOWN_LEFT_SPIKE COL_DEATH COL_RIGHT COL_LEFT COL_UP_RIGHT_SPIKE COL_UP_LEFT_SPIKE COL_DEATH COL_ALL COL_LEFT COL_DOWN_RIGHT COL_DOWN_LEFT"""

col_table = re.findall(r'COL_\w+', collision_names_raw)

def get_collision(tmx_tid):
    if tmx_tid == 0: return "."
    local = tmx_tid - 1
    if local in (0xDF, 0xE3, 0xFE, 0xFF): local = 0x00
    elif local == 0xFD: local = 0x26
    if local < len(col_table): return col_table[local]
    return f"?{local}"

layers = root.findall('layer')
tl = layers[0]
w = int(tl.get('width'))
tiles = [int(x) for x in tl.find('data').text.strip().split(',')]

# Check row 11-12 for FLOOR_CEIL gaps between cols 440-575
print("=== FLOOR_CEIL boundary check (rows 11-12) ===")
print(f"Col range 440-575 (X=7040-9200)")
print()
for r in [11, 12]:
    gaps = []
    for c in range(440, 576):
        tid = tiles[r * w + c]
        cname = get_collision(tid)
        is_fc = ("FLOOR_CEIL" in cname) if cname != "." else False
        if not is_fc:
            gaps.append(c)
    if gaps:
        # Show ranges
        ranges = []
        start = gaps[0]
        prev = gaps[0]
        for g in gaps[1:]:
            if g == prev + 1:
                prev = g
            else:
                ranges.append((start, prev))
                start = g
                prev = g
        ranges.append((start, prev))
        print(f"Row {r} (Y={r*16}): OPEN at cols {ranges}")
    else:
        print(f"Row {r} (Y={r*16}): FLOOR_CEIL everywhere 440-575")

# Also check for sprites in the lower corridor
sp_layer = layers[1]  # SP layer
sp_w = int(sp_layer.get('width'))
sp_tiles = [int(x) for x in sp_layer.find('data').text.strip().split(',')]

print("\n=== Sprites in lower corridor zone (rows 11-22, cols 440-575) ===")
for r in range(11, 23):
    for c in range(440, 576):
        tid = sp_tiles[r * sp_w + c]
        if tid > 0:
            local = tid - 257  # sprites tileset firstgid=257
            print(f"  r{r} c{c} (X={c*16}, Y={r*16}): SP tile {tid} (local=0x{local:02X})")
